spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://0.0.0.0:5436/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_USER:qwerty}
    driver-class-name: "org.postgresql.Driver"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
  application:
    name: spring-boot-module-server
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    clear-checksums: true
    enabled: true
#  spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
#  spring.liquibase.clear-checksums=true
#  spring.liquibase.enabled=true
#
#  spring.jpa.show-sql=true
#  spring.jpa.properties.hibernate.format_sql=true
#  spring.jpa.hibernate.ddl-auto=create
#
#  spring.datasource.url=jdbc:postgresql://0.0.0.0:5434/postgres
#  spring.datasource.username=postgres
#  spring.datasource.password=qwerty
#
#  spring.datasource.driver-class-name=org.postgresql.Driver
#  spring.jpa.database=postgresql
#  spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
#
#  spring.application.name=spring-boot-module-server
#  server.port=8080
#  spring.cloud.consul.host=localhost
#  spring.cloud.consul.port=8500
#  spring.cloud.consul.discovery.instance-id=${spring.application.name}:${random.value}

