create table users
(
    id       int4 generated by default as identity,
    lastname varchar(255),
    login    varchar(255),
    name     varchar(255),
    pass     varchar(255),
    phone    varchar(255),
    primary key (id)
)

GO